# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# 例行变更
name: 研报抓取

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Asia/Shanghai

permissions:
  contents: read

jobs:
  report_build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up SSH key for cloning repoA
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      
    - name: Add github.com to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts   
        
    - name: clone report
      run: |
        chmod +x clone_report.sh
        ./clone_report.sh
    - name: generate report
      run: |
        python run.py
    - name: upload report
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        create-target-branch-if-needed: true
        source-directory: 'gen_report'
        destination-github-username: 'manymore13'
        destination-repository-name: 'report'
        target-branch: main
        commit-message: "东财行业研报更新"
            
          
    
